
import Head from "next/head";
import Navbar from "./Navbar";

export default function Layout({ title = null, children, isNavbarVisibile = true }) {
let titulo = "Products" + (title ? " - " + title : "")

  return (
    <div className="dark:dark light">
      <Head>
        <title>{titulo}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isNavbarVisibile &&  <Navbar></Navbar>}
      <main >{children}</main>
    </div>
  );
}
