
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./Navbar";

export default function Layout({ title, children }) {
  return (
    <div className="light dark:dark">
     
      <Head>
        <title>Create Next App{title ? " - " + title : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <main className={styles.main}>{children}</main>
    </div>
  );
}
