import { useContext } from "react";
import { useForm } from "react-hook-form";
import { AuthContext } from "../components/auth/AuthContext";
import { parseCookies } from "nookies";
import Head from "next/head";

export default function SinginPage() {
  const { register, handleSubmit } = useForm();

  const { singin } = useContext(AuthContext);

  const submitForm = async (data) => {
    await singin(data);
  };

  return (
    <div className="flex justify-center items-center h-screen">
      <Head>
        <title>Create Next App - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form
        className="bg-neutral-800 dark:bg-white dark:text-neutral-900 p-2 rounded"
        onSubmit={handleSubmit(submitForm)}
      >
        <div>
          <input
            {...register("email")}
            type={"email"}
            name="email"
            placeholder="email"
            className="p-2"
          ></input>
        </div>
        <div>
          <input
            {...register("password")}
            type={"password"}
            name="password"
            placeholder="password"
            className="p-2"
          ></input>
        </div>
        <button className="p-2 w-full hover:bg-slate-400 rounded">
          Logearse
        </button>
      </form>
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  const { Token } = parseCookies(ctx);
  if (Token !== undefined) {
    return {
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};
