import { useContext, useState } from "react";
import { useForm } from "react-hook-form";
import { AuthContext } from "../components/auth/AuthContext";
import { parseCookies } from "nookies";
import Head from "next/head";
import { useRouter } from "next/router";

export default function SinginPage() {
  const router = useRouter();

  const { Token } = parseCookies();
  if (Token !== undefined) {
    router.push("/dashboard");
  } 

  const [isloading, setisloagind] = useState(false);
    const [erro, setError] = useState(false)
    const { register, handleSubmit } = useForm();

    const { singin } = useContext(AuthContext);

    const submitForm = async (data) => {
      setisloagind(true);
      try {
        await singin(data);
        setError(false)
      } catch (error) {
       setError(true)
      }
      setisloagind(false);
    };

    return (
      <div className="flex justify-center items-center h-screen">
        <Head>
          <title>Create Next App - Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <form
          className="bg-neutral-800 dark:bg-white dark:text-neutral-900 p-2 rounded"
          onSubmit={handleSubmit(submitForm)}
        >
          <div>
            <input
              {...register("email")}
              type={"email"}
              name="email"
              placeholder="email"
              className="p-2"
            ></input>
          </div>
          <div>
            <input
              {...register("password")}
              type={"password"}
              name="password"
              placeholder="password"
              className="p-2"
            ></input>
          </div>
          <button className="p-2 w-full hover:bg-slate-400 rounded">
            Logearse
          </button>
        <div>
        {isloading && <p>cargando</p>}
        </div>
        <div>
        {erro && <p>Login Error</p>}
        </div>
        </form>
      </div>
    );
}
